// Generated by gencpp from file hw_1/Message.msg
// DO NOT EDIT!


#ifndef HW_1_MESSAGE_MESSAGE_H
#define HW_1_MESSAGE_MESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hw_1
{
template <class ContainerAllocator>
struct Message_
{
  typedef Message_<ContainerAllocator> Type;

  Message_()
    : message()
    , sid(0)  {
    }
  Message_(const ContainerAllocator& _alloc)
    : message(_alloc)
    , sid(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef int32_t _sid_type;
  _sid_type sid;





  typedef boost::shared_ptr< ::hw_1::Message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hw_1::Message_<ContainerAllocator> const> ConstPtr;

}; // struct Message_

typedef ::hw_1::Message_<std::allocator<void> > Message;

typedef boost::shared_ptr< ::hw_1::Message > MessagePtr;
typedef boost::shared_ptr< ::hw_1::Message const> MessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hw_1::Message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hw_1::Message_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hw_1::Message_<ContainerAllocator1> & lhs, const ::hw_1::Message_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message &&
    lhs.sid == rhs.sid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hw_1::Message_<ContainerAllocator1> & lhs, const ::hw_1::Message_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hw_1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hw_1::Message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw_1::Message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw_1::Message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw_1::Message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw_1::Message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw_1::Message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hw_1::Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59e1119311361fcdf825364a68bdb07e";
  }

  static const char* value(const ::hw_1::Message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59e1119311361fcdULL;
  static const uint64_t static_value2 = 0xf825364a68bdb07eULL;
};

template<class ContainerAllocator>
struct DataType< ::hw_1::Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hw_1/Message";
  }

  static const char* value(const ::hw_1::Message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hw_1::Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
"int32 sid\n"
;
  }

  static const char* value(const ::hw_1::Message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hw_1::Message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.sid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hw_1::Message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hw_1::Message_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "sid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HW_1_MESSAGE_MESSAGE_H
